apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mkk0ffs37-python 
  janus-idp.io/tekton: mkk0ffs37-python
  backstage.io/kubernetes-id: mkk0ffs37-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mkk0ffs37-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  