apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mkk0ffs37-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mkk0ffs37-python 
  name: mkk0ffs37-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mkk0ffs37-python 
